# Generated by Django 6.0.8 on 2026-08-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=500)),
                ('audience', models.CharField(choices=[('all', 'All users'), ('cart_abandoners', 'Cart abandoners'), ('gold_platinum', 'Gold + Platinum'), ('transactional', 'Transactional')], default='all', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('placement', models.CharField(choices=[('home_carousel', 'Home carousel'), ('category_strip', 'Category strip'), ('profile', 'Profile')], default='home_carousel', max_length=20)),
                ('link_screen', models.CharField(blank=True, help_text="Deep-link target, e.g. 'category_list'.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.category')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('min_order_value', models.PositiveIntegerField(default=0)),
                ('flat_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('percent_discount', models.PositiveIntegerField(blank=True, help_text='0-100', null=True)),
                ('max_discount', models.PositiveIntegerField(blank=True, help_text='Cap applied to percent_discount.', null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('terms', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('zones', models.ManyToManyField(blank=True, help_text='Empty = all zones.', related_name='coupons', to='zones.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
