# Generated by Django 4.2.30 on 2026-08-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_coupon_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='zones',
        ),
    ]
