# Generated by Django 4.2.30 on 2026-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_remove_coupon_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('key', models.CharField(choices=[('diwali', 'Diwali'), ('holi', 'Holi'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('independence_day', 'Independence Day'), ('raksha_bandhan', 'Raksha Bandhan')], max_length=30, unique=True)),
                ('override_mode', models.CharField(choices=[('auto', 'Auto — by calendar date'), ('force_on', 'Always on'), ('force_off', 'Always off')], default='auto', max_length=10)),
                ('starts_on', models.DateField(blank=True, help_text="'Auto' mode only. Overrides the app's built-in date window for this year (handy for Diwali/Holi/Raksha Bandhan, which move every year). Leave both dates blank to keep using the app's built-in window.", null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('accent_color', models.CharField(default='#F3B14A', help_text='Hex, e.g. #F3B14A', max_length=9)),
                ('gradient_start', models.CharField(default='#173C6E', help_text='Header gradient, near corner.', max_length=9)),
                ('gradient_end', models.CharField(default='#0A1F3C', help_text='Header gradient, far corner.', max_length=9)),
                ('motif', models.CharField(choices=[('diyaLights', 'Diya / string lights'), ('colorSplash', 'Colour splash'), ('snowfall', 'Snowfall'), ('confetti', 'Confetti')], default='diyaLights', max_length=15)),
                ('greeting_text', models.CharField(blank=True, help_text='Short badge shown in the home header.', max_length=120)),
                ('popup_enabled', models.BooleanField(default=True, help_text='Show the one-time popup on app open, not just the header badge.')),
                ('popup_title', models.CharField(blank=True, max_length=120)),
                ('popup_message', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
