# Generated by Django 6.0.8 on 2026-08-05 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('partner_code', models.CharField(help_text="e.g. 'BSK-DP-2210'", max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('vehicle', models.CharField(choices=[('bike', 'Motorbike'), ('scooter', 'Scooter'), ('bicycle', 'Bicycle')], default='bike', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On trip'), ('off_duty', 'Off duty')], default='off_duty', max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner_profile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_partners', to='zones.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
