# Generated by Django 4.2.30 on 2026-09-20 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_zone'),
        ('accounts', '0003_profile_email_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Denormalized balance, kept in sync with LoyaltyTransaction via F()-expression updates (see LoyaltyTransaction.award_for_order/redeem) — never edit directly.'),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('points', models.IntegerField(help_text='Positive = earned, negative = redeemed.')),
                ('reason', models.CharField(choices=[('order_reward', 'Order reward'), ('redeemed', 'Redeemed for coupon')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
