"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import cloudinary
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a .env file at the project root into os.environ
# (copy .env.example to .env and fill in real values).
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-@prt81o3s^0f1@#@ly5b*r2gnbrp+@lb+z=@t)8=+ong^sm_f*",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")

# Auth here is JWT-in-header (djangorestframework-simplejwt), never cookies,
# so a wide-open CORS policy doesn't carry the usual CSRF-via-cookie risk —
# it just lets the Flutter web build (served from a LAN IP + changing dev
# port, e.g. http://192.168.9.153:8766) call this API at all. Tighten to
# explicit origins via CORS_ALLOWED_ORIGINS once DJANGO_DEBUG is off.
CORS_ALLOW_ALL_ORIGINS = DEBUG or os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False") == "True"
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_spectacular',

    'accounts',
    'zones',
    'catalog',
    'delivery',
    'cart',
    'orders',
    'promotions',
    'reports',
    'support',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # As high as possible, and before CommonMiddleware — CORS headers must
    # land on preflight (OPTIONS) responses too, which CommonMiddleware's
    # redirects would otherwise short-circuit without them.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Postgres (Neon) only — set DATABASE_URL in .env. No sqlite fallback.

DATABASES = {
    'default': dj_database_url.parse(
        os.environ["DATABASE_URL"],
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Custom User model
# ---------------------------------------------------------------------------
AUTH_USER_MODEL = "accounts.User"


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_RATES": {
        # applies to SendOTPView / ResendOTPView / VerifyOTPView / MasterOTPLoginView
        "otp": "10/min",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_PAGINATION_CLASS": "core.pagination.DefaultPagination",
    "PAGE_SIZE": 20,
}

# ---------------------------------------------------------------------------
# drf-spectacular (OpenAPI schema + Swagger UI / Redoc docs)
# ---------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "Mobile OTP Login API",
    "DESCRIPTION": (
        "Mobile number + OTP login (send/resend/verify), a master-OTP "
        "bypass for QA/testing, and profile/address/GPS-location management."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True},
    "COMPONENT_SPLIT_REQUEST": True,
    "TAGS": [
        {"name": "Auth - OTP", "description": "Send/resend/verify OTP and master-OTP login"},
        {"name": "Profile", "description": "The logged-in user's profile"},
        {"name": "Addresses", "description": "Multiple addresses stored on the profile"},
        {"name": "GPS Locations", "description": "Multiple saved GPS points stored on the profile"},
        {"name": "Customers", "description": "Admin-only customer directory with order stats"},
        {"name": "Catalog - Categories", "description": "Categories/subcategories (public read, admin write)"},
        {"name": "Catalog - Products", "description": "Products (public read, admin write)"},
        {"name": "Catalog - Reviews", "description": "Product reviews (public read, customer write)"},
        {"name": "Catalog - Inventory", "description": "Per-zone stock levels (admin-only)"},
        {"name": "Zones & Stores", "description": "Dark stores / delivery zones"},
        {"name": "Delivery Partners", "description": "Delivery partner roster (admin-only)"},
        {"name": "Cart", "description": "The logged-in customer's cart"},
        {"name": "Wishlist", "description": "The logged-in customer's saved products"},
        {"name": "Orders", "description": "Placing, tracking, and (admin) managing orders"},
        {"name": "Promotions - Coupons", "description": "Coupons (public read, admin write)"},
        {"name": "Promotions - Banners", "description": "Home/category banners (public read, admin write)"},
        {"name": "Promotions - Notifications", "description": "Push campaigns (admin compose/send)"},
        {"name": "Admin Reports", "description": "Dashboard/sales/GST aggregate reports (admin-only)"},
        {"name": "Support", "description": "Support tickets"},
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
}


# ---------------------------------------------------------------------------
# OTP configuration
# ---------------------------------------------------------------------------
OTP_LENGTH = int(os.environ.get("OTP_LENGTH", 4))
OTP_EXPIRY_MINUTES = int(os.environ.get("OTP_EXPIRY_MINUTES", 5))
MAX_OTP_ATTEMPTS = int(os.environ.get("MAX_OTP_ATTEMPTS", 3))
RESEND_OTP_WAIT_SECONDS = int(os.environ.get("RESEND_OTP_WAIT_SECONDS", 30))

# "Master OTP" — a fixed code that always logs a user in WITHOUT sending any
# real SMS. Handy for QA / app-store review / staging test accounts.
# CHANGE THIS in production and keep it secret (env var, not source control).
MASTER_OTP = os.environ.get("MASTER_OTP", "123456")

# Leave empty to allow the master OTP for ANY mobile number.
# Or restrict it to specific test numbers, e.g. ["+919999999999", "+911234567890"]
MASTER_OTP_MOBILE_NUMBERS = [
    n for n in os.environ.get("MASTER_OTP_MOBILE_NUMBERS", "9718751020").split(",") if n
]


# ---------------------------------------------------------------------------
# SMS provider configuration
# ---------------------------------------------------------------------------
# "console" just prints/logs the OTP — perfect for local development.
# "whatsapp" sends via MSG91's WhatsApp Business API — no DLT needed, but
# needs a verified WhatsApp Business number + an approved WhatsApp template.
SMS_BACKEND = os.environ.get("SMS_BACKEND", "console")

MSG91_AUTH_KEY = os.environ.get("MSG91_AUTH_KEY", "")

# MSG91 WhatsApp Business API (used when SMS_BACKEND="whatsapp").
# MSG91_WHATSAPP_NUMBER is the verified WhatsApp Business number connected
# in MSG91's dashboard (WhatsApp -> Manage Numbers); MSG91_WHATSAPP_TEMPLATE
# is the name of an approved "Authentication" category template with one
# body variable for the code.
MSG91_WHATSAPP_NUMBER = os.environ.get("MSG91_WHATSAPP_NUMBER", "")
MSG91_WHATSAPP_TEMPLATE = os.environ.get("MSG91_WHATSAPP_TEMPLATE", "")


# ---------------------------------------------------------------------------
# Push notifications (Firebase Cloud Messaging)
# ---------------------------------------------------------------------------
# Path to the Firebase service-account JSON key (Firebase console -> Project
# settings -> Service accounts -> Generate new private key). Keep this file
# OUT of source control — point the env var at wherever you actually put it.
# Push sends are a no-op (logged, not an error) when this isn't set, so
# local dev works without a key. A relative path is resolved against
# BASE_DIR so it works regardless of the process's working directory
# (e.g. deployed on Vercel vs. `python manage.py runserver` locally).
_firebase_creds = os.environ.get("FIREBASE_CREDENTIALS_PATH", "")
FIREBASE_CREDENTIALS_PATH = str(BASE_DIR / _firebase_creds) if _firebase_creds and not os.path.isabs(_firebase_creds) else _firebase_creds


# ---------------------------------------------------------------------------
# Cloudinary (image storage for catalog product images)
# ---------------------------------------------------------------------------
# Used by core/helper/cloudinary_service.py — uploads go straight to
# Cloudinary and only the returned secure_url is persisted in our DB
# (Product.main_image_url / ProductImage.image_url are plain URLFields).
CLOUDINARY_CLOUD_NAME = os.environ.get("CLOUDINARY_CLOUD_NAME", "")
CLOUDINARY_API_KEY = os.environ.get("CLOUDINARY_API_KEY", "")
CLOUDINARY_API_SECRET = os.environ.get("CLOUDINARY_API_SECRET", "")
# Unsigned upload preset (Cloudinary dashboard → Settings → Upload →
# Upload presets, mode "Unsigned"). Used instead of the API key/secret so
# uploads work regardless of that key's action scopes.
CLOUDINARY_UPLOAD_PRESET = os.environ.get("CLOUDINARY_UPLOAD_PRESET", "uploads")

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True,
)
