# Generated by Django 4.2.30 on 2026-09-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, help_text="With country code, e.g. +919718751020 — used for the 'Call support' tel: link.", max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only with country code, e.g. 919718751020 — used to build the wa.me link.', max_length=20)),
                ('chat_url', models.URLField(blank=True, help_text='External live-chat URL (e.g. a Tawk.to/Crisp/Intercom widget page). Leave blank to hide the chat button.')),
                ('reply_time_label', models.CharField(blank=True, default='Typical reply in under 2 min', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
