# Generated by Django 4.2.30 on 2026-09-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportconfig',
            name='chat_url',
        ),
        migrations.AddField(
            model_name='supportconfig',
            name='whatsapp_message',
            field=models.CharField(blank=True, default='Hi, I need help with my Aapno Bazar order.', help_text='Pre-filled text the WhatsApp chat opens with.', max_length=300),
        ),
    ]
