# Generated by Django 4.2.30 on 2026-09-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_supportconfig_chat_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Support FAQ',
                'verbose_name_plural': 'Support FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='supportconfig',
            name='whatsapp_message',
            field=models.CharField(blank=True, default='Hey, I am {name} and I need help.', help_text="Pre-filled text the WhatsApp chat opens with. Include the literal '{name}' placeholder to have it replaced with the signed-in customer's own name (see SupportConfigSerializer.get_whatsapp_link).", max_length=300),
        ),
    ]
