# Generated by Django 4.2.30 on 2026-08-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_more_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure_url — set via /images/upload/.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure_url — set via /images/upload/.'),
        ),
    ]
