# Generated by Django 4.2.30 on 2026-08-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_icon_subcategory_image_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, help_text='Manual override; real stock lives in ProductStock.'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product'),
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='zone',
        ),
    ]
