# Generated by Django 4.2.30 on 2026-08-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_failure_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cod', 'COD'), ('qr', 'QR'), ('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet')], default='qr', max_length=10),
        ),
    ]
