# Generated by Django 4.2.30 on 2026-08-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
