# Generated by Django 4.2.30 on 2026-08-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zone',
        ),
    ]
