# Generated by Django 6.0.8 on 2026-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="e.g. 'Koramangala dark store'", max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('pincodes', models.JSONField(blank=True, default=list, help_text='e.g. ["560034", "560095"]')),
                ('avg_eta_minutes', models.PositiveIntegerField(default=12)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
