# Generated by Django 4.2.30 on 2026-08-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productstock_unique_together_and_more'),
        ('promotions', '0003_remove_coupon_zones'),
        ('delivery', '0002_remove_deliverypartner_zone'),
        ('orders', '0007_remove_order_zone'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
